### ISSUE TITLE
Freeze when can't read disc. 

### ISSUE THREAD

**Issue by tic13** [socram8888/tonyhax#49]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 - Are you using CD-R media, and not CD-RW?
 - Did you copy all the files in the expected format to the memory card?

Yes philips cd-r (he don't like it) 

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
1.1.2

**Installation method**: How did you get tonyhax on the memory card?

Ulaunch elf 
**Entry point game**: Which game are you using to launch tonyhax?

Many. 

**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"

Scph-30004 ps2 V3. 

**Integrity check**: If it boots, does the built-in integrity check succeed?

Yes

**BIOS version**: If you can get to boot, which version of the BIOS does it report?

09/02/00 E

**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

It happend if for some reason the ps2 can read the disc..

**Bug explanation**:
If the ps2 can't read the cd-r for some reason. (he don't like the medium or some equivalent).

The program stuck in initialize the cd don't matter you open and change the disc it stuck and you only can reset the console. 

Same happend if you don't put a cd in. He try initialize cd and stuck. (this can happend if for some bad luck the ps2 open and close the tray fast itself).

**Comment by socram8888** [comment]
That is fixed in the latest version. Please don't fill the issue tracker with crap. Thanks

**Comment by tic13** [comment]
Oh man sorry. I don't know a new version was release. I was thinking I have the last(I install it yesterday).

Sorry!.

**Comment by tic13** [comment]
I have installed the 1.2.3 its not fixed.Maybe you speak about another bug?. Its freeeze in same manner.

**Comment by socram8888** [comment]
Ah alright. The bug that I fixed is that if the console can read the disc but for some compatibility reason it fails to boot, it'll retry just fine.

However if it gets stuck in the "initializing CD" prompt, it'll get stuck forever. In that point I just call the BIOS to read the CD filesystem, and if the BIOS doesn't fail gracefully and return me the control there's really nothing I can do.

**Comment by tic13** [comment]
Not sure if can work,maybe you need send a simply command directly  to the cd-rom controller and read the status.

no cash$ doc tells.

80h appears on some commands (02h..09h, 0Bh..0Dh, 10h..16h, 1Ah, 1Bh?, and 1Dh) when the disk is missing, or when the drive unit is disconnected from the mainboard.

So if the command return 80  you can asume there is not disk present or can't be read show a mesage and dont excute initcd.
